// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return FirebaseOptions(
      apiKey: 'AIzaSyB6Vg6taakUfEj2uqs1HAdFg_uG4_J7aeQ',
      appId: '1:464928903616:web:739a12155d82eef89d7825',
      messagingSenderId: '464928903616',
      projectId: 'lumin-business',
      authDomain: 'lumin-business.firebaseapp.com',
      storageBucket: 'lumin-business.appspot.com',
    );
  }
}
